### ISSUE TITLE
DevRel community contribution guide

### ISSUE THREAD

**Issue by Cheukting** [ossf/DevRel-community#30]
As per our last meeting, it will be useful to have a contribution guide for the DEvRel community. It can be a md file. Potential content includes how to present OpenSSF and related security topics in giving talks, where to find the events that we are going to, how to let us know if someone is speaking etc. It can also include the link to the [meetup organising guide](https://openssf.org/community/meetup-guidelines/).

**Comment by webchick** [comment]
Here is a stab: https://docs.google.com/document/d/100EI-QXJ4OESVjGQngJsVYYusrcDcHJppQ-K69Er-Ic/edit

**Comment by webchick** [comment]
Ok, thanks to @kdruckman for the feedback, this stab is now a PR for review at #37

**Comment by webchick** [comment]
The PR got merged, so closing this one out!
