### ISSUE TITLE
meeting minutes name is inconsistent for 2024 Jan 01st

### ISSUE THREAD

**Issue by nikitakoselev** [ossf/DevRel-community#40]
The meeting minutes seem to normally be in yyyymmdd format, but this specific file is misspelled as it describes January event.
https://github.com/ossf/DevRel-community/blob/main/meetings/2024/20241101.md

The file must be renamed into 20240111.md 
![DevRel-community screenshot](https://github.com/ossf/DevRel-community/assets/6383738/95163f37-c01e-47d6-a056-e19bdb97813c)

**Comment by nikitakoselev** [comment]
A pull request has been raised: https://github.com/ossf/DevRel-community/pull/41

**Comment by webchick** [comment]
Yay! Thanks so much for the fix, and welcome to the DevRel Community! :D
