### ISSUE TITLE
New subfolder - meetings

### ISSUE THREAD

**Issue by edodusi** [ossf/DevRel-community#5]
We should add a new subfolder called `meetings` and put minutes of each meeting we have as markdown files in there.

I will do this if allowed.

**Comment by hythloda** [comment]
@edodusi you are more than welcome to do this! We are looking at who should be in at what level so what level do you want to be in on :)

- contributor ?
- maintainer ? 

We can then add you to the team and get you up and running!

**Comment by Cheukting** [comment]
@edodusi thank you! You are now a maintainer :-)

**Comment by edodusi** [comment]
@Cheukting are you sure? Apparently I don't have write access to the repo...

> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by hythloda** [comment]
> nce in new issue
> Edit
> Hide
> Delete

check your email, you should see in invite to join the team

**Comment by edodusi** [comment]
Nope...please check that you are inviting my GitHub account and not my work email

**Comment by hythloda** [comment]
GitHub invites are notorious for getting lost :) best place to see them is at your "org" level if you ever miss the email https://github.com/settings/organizations
